### ISSUE TITLE
[BUG] Does not support: 204 No Content

### ISSUE THREAD

**Issue by slatermorgan** [JaredCE/serverless-openapi-documenter#187]
**Describe the bug**
I don't think we currently support definitions for endpoints which return "No Content". 

I get `Error: hugoboss-requests-dev-patchStatus is missing a Response Model for statusCode 204`

**To Reproduce**
```
handler: lambda/functions/patchStatus/main.go
timeout: 30
events:
  - http:
      path: /v1/request/{id}/status/{subId}
      method: patch
      cors: true
      private: true

      documentation:
        summary: "Patch Status"
        description: "updates a status"
        pathParams:
          - name: "id"
            description: "The id of the request to mark as complete"
            required: true
            schema:
              type: "string"
          - name: "subId"
            description: "The status you want to apply to a request"
            required: true
            schema:
              type: "string"
        requestModels:
          "application/json": "RequestStatusRequest"
        methodResponses:
          - statusCode: "204"
            responseBody:
              description: No content
          - statusCode: "404"
            responseBody:
              description: Not found
            responseModels:
              "application/json": "RequestServiceError"
          - statusCode: "400"
            responseBody:
              description: Bad request
            responseModels:
              "application/json": "RequestServiceError"

```
**Expected behavior**
I would expect to be able to define a response without a model like the example [here](https://swagger.io/docs/specification/describing-responses/).

```
        '204':
          description: The resource was deleted successfully.
```
"Some responses, such as 204 No Content, have no body. To indicate the response body is empty, do not specify a content for the response"

**Desktop (please complete the following information):**
 - Serverless version: 3.36.0
 - serverless-openapi-documenter version 0.0.93

**Additional context**

**Comment by slatermorgan** [comment]
https://github.com/JaredCE/serverless-openapi-documenter/pull/189

**Comment by JaredCE** [comment]
I have fixed this with release 0.0.94.  I figure any response could be empty, not just 204, so best to accept them all

**Comment by slatermorgan** [comment]
Thank @JaredCE

**Comment by slatermorgan** [comment]
@JaredCE sorry what would this look like then?

```
        methodResponses:
          - statusCode: "204"
            responseBody:
              description: No content
```

still throws an error
